from PyQt5 import QtCore, QtGui, QtWidgets


class RegisterForm(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(313, 187)
        MainWindow.setMinimumSize(QtCore.QSize(249, 187))
        MainWindow.setMaximumSize(QtCore.QSize(313, 187))
        font = QtGui.QFont()
        font.setFamily("TOYZ")
        font.setPointSize(11)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.register2bt = QtWidgets.QPushButton(self.centralwidget)
        self.register2bt.setGeometry(QtCore.QRect(10, 110, 211, 23))
        self.register2bt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.register2bt.setObjectName("register2bt")
        self.registelb = QtWidgets.QLabel(self.centralwidget)
        self.registelb.setGeometry(QtCore.QRect(10, 10, 291, 16))
        self.registelb.setObjectName("registelb")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 291, 80))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(9)
        self.gridLayout.setObjectName("gridLayout")
        self.loginle = QtWidgets.QLineEdit(self.layoutWidget)
        self.loginle.setObjectName("loginle")
        self.gridLayout.addWidget(self.loginle, 0, 1, 1, 1)
        self.passwordlb = QtWidgets.QLabel(self.layoutWidget)
        self.passwordlb.setObjectName("passwordlb")
        self.gridLayout.addWidget(self.passwordlb, 1, 0, 1, 1)
        self.passwordle = QtWidgets.QLineEdit(self.layoutWidget)
        self.passwordle.setObjectName("passwordle")
        self.gridLayout.addWidget(self.passwordle, 1, 1, 1, 1)
        self.loginlb = QtWidgets.QLabel(self.layoutWidget)
        self.loginlb.setObjectName("loginlb")
        self.gridLayout.addWidget(self.loginlb, 0, 0, 1, 1)
        self.password2lb = QtWidgets.QLabel(self.layoutWidget)
        self.password2lb.setObjectName("password2lb")
        self.gridLayout.addWidget(self.password2lb, 2, 0, 1, 1)
        self.password2le = QtWidgets.QLineEdit(self.layoutWidget)
        self.password2le.setObjectName("password2le")
        self.gridLayout.addWidget(self.password2le, 2, 1, 1, 1)
        self.returnbt = QtWidgets.QPushButton(self.centralwidget)
        self.returnbt.setGeometry(QtCore.QRect(10, 140, 101, 23))
        self.returnbt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.returnbt.setObjectName("returnbt")
        self.help = QtWidgets.QPushButton(self.centralwidget)
        self.help.setGeometry(QtCore.QRect(120, 140, 101, 23))
        self.help.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.help.setObjectName("help")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Best Clicker"))
        self.register2bt.setText(_translate("MainWindow", "Зарегистрироваться"))
        self.registelb.setText(_translate("MainWindow", "Зарегестрируйте аккаунт"))
        self.passwordlb.setText(_translate("MainWindow", "Пароль:"))
        self.loginlb.setText(_translate("MainWindow", "Логин:"))
        self.password2lb.setText(_translate("MainWindow", "Повторите пароль:"))
        self.returnbt.setText(_translate("MainWindow", "Назад"))
        self.help.setText(_translate("MainWindow", "Помощь"))
