from PyQt5 import QtCore, QtGui, QtWidgets


class SettingsForm(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(260, 232)
        MainWindow.setMinimumSize(QtCore.QSize(260, 232))
        MainWindow.setMaximumSize(QtCore.QSize(260, 232))
        font = QtGui.QFont()
        font.setFamily("TOYZ")
        font.setPointSize(11)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bttutorial = QtWidgets.QPushButton(self.centralwidget)
        self.bttutorial.setGeometry(QtCore.QRect(10, 180, 241, 23))
        self.bttutorial.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bttutorial.setObjectName("bttutorial")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 110, 241, 71))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.slidermusic = QtWidgets.QSlider(self.layoutWidget)
        self.slidermusic.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.slidermusic.setMinimum(0)
        self.slidermusic.setMaximum(100)
        self.slidermusic.setProperty("value", 100)
        self.slidermusic.setOrientation(QtCore.Qt.Horizontal)
        self.slidermusic.setObjectName("slidermusic")
        self.gridLayout.addWidget(self.slidermusic, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 2)
        self.Slidersound = QtWidgets.QSlider(self.layoutWidget)
        self.Slidersound.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Slidersound.setMinimum(0)
        self.Slidersound.setMaximum(100)
        self.Slidersound.setProperty("value", 100)
        self.Slidersound.setOrientation(QtCore.Qt.Horizontal)
        self.Slidersound.setObjectName("Slidersound")
        self.gridLayout.addWidget(self.Slidersound, 1, 2, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 241, 100))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.keyssoud = QtWidgets.QKeySequenceEdit(self.layoutWidget1)
        self.keyssoud.setEnabled(False)
        self.keyssoud.setObjectName("keyssoud")
        self.gridLayout_2.addWidget(self.keyssoud, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 2)
        self.keysmusic = QtWidgets.QKeySequenceEdit(self.layoutWidget1)
        self.keysmusic.setEnabled(False)
        self.keysmusic.setObjectName("keysmusic")
        self.gridLayout_2.addWidget(self.keysmusic, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 2)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 204, 243, 26))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.clearak = QtWidgets.QPushButton(self.layoutWidget2)
        self.clearak.setObjectName("clearak")
        self.horizontalLayout.addWidget(self.clearak)
        self.delak = QtWidgets.QPushButton(self.layoutWidget2)
        self.delak.setObjectName("delak")
        self.horizontalLayout.addWidget(self.delak)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Настройки"))
        self.bttutorial.setText(_translate("MainWindow", "Повторить туториал"))
        self.label_3.setText(_translate("MainWindow", "Музыка:"))
        self.label_2.setText(_translate("MainWindow", "Звук:"))
        self.keyssoud.setKeySequence(_translate("MainWindow", "N"))
        self.label_5.setText(_translate("MainWindow", "Вкл/выкл звук"))
        self.keysmusic.setKeySequence(_translate("MainWindow", "M"))
        self.label_6.setText(_translate("MainWindow", "Вкл/выкл музыку"))
        self.clearak.setText(_translate("MainWindow", "Очистить ак"))
        self.delak.setText(_translate("MainWindow", "Удалить ак"))
