from PyQt5 import QtCore, QtGui, QtWidgets


class ShopForm(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(611, 335)
        MainWindow.setMinimumSize(QtCore.QSize(611, 335))
        MainWindow.setMaximumSize(QtCore.QSize(611, 335))
        MainWindow.setSizeIncrement(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("TOYZ")
        font.setPointSize(12)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 7, 371, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(33)
        self.gridLayout.setObjectName("gridLayout")
        self.clicklb = QtWidgets.QLabel(self.layoutWidget)
        self.clicklb.setObjectName("clicklb")
        self.gridLayout.addWidget(self.clicklb, 0, 0, 1, 1)
        self.autoclickup = QtWidgets.QPushButton(self.layoutWidget)
        self.autoclickup.setObjectName("autoclickup")
        self.gridLayout.addWidget(self.autoclickup, 1, 1, 1, 1)
        self.energyup = QtWidgets.QPushButton(self.layoutWidget)
        self.energyup.setObjectName("energyup")
        self.gridLayout.addWidget(self.energyup, 2, 1, 1, 1)
        self.clickup = QtWidgets.QPushButton(self.layoutWidget)
        self.clickup.setEnabled(True)
        self.clickup.setObjectName("clickup")
        self.gridLayout.addWidget(self.clickup, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.autolb = QtWidgets.QLabel(self.layoutWidget)
        self.autolb.setObjectName("autolb")
        self.gridLayout.addWidget(self.autolb, 1, 0, 1, 1)
        self.Leaderboard = QtWidgets.QTableWidget(self.centralwidget)
        self.Leaderboard.setEnabled(True)
        self.Leaderboard.setGeometry(QtCore.QRect(10, 127, 441, 201))
        self.Leaderboard.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.Leaderboard.setCornerButtonEnabled(True)
        self.Leaderboard.setObjectName("Leaderboard")
        self.Leaderboard.setColumnCount(5)
        self.Leaderboard.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.Leaderboard.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Leaderboard.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Leaderboard.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Leaderboard.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Leaderboard.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Leaderboard.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Leaderboard.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.Leaderboard.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.Leaderboard.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.Leaderboard.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.Leaderboard.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Leaderboard.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Leaderboard.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Leaderboard.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Leaderboard.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Leaderboard.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Leaderboard.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Leaderboard.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Leaderboard.setItem(0, 4, item)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(456, 130, 31, 201))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(QtCore.Qt.Vertical)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.skin = QtWidgets.QLabel(self.centralwidget)
        self.skin.setGeometry(QtCore.QRect(490, 207, 120, 120))
        self.skin.setText("")
        self.skin.setPixmap(QtGui.QPixmap("../images/coockie.png"))
        self.skin.setObjectName("skin")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(490, 101, 121, 103))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.buyskin = QtWidgets.QPushButton(self.layoutWidget1)
        self.buyskin.setObjectName("buyskin")
        self.verticalLayout.addWidget(self.buyskin)
        self.changeskin = QtWidgets.QPushButton(self.layoutWidget1)
        self.changeskin.setObjectName("changeskin")
        self.verticalLayout.addWidget(self.changeskin)
        self.leftskins = QtWidgets.QPushButton(self.layoutWidget1)
        self.leftskins.setObjectName("leftskins")
        self.verticalLayout.addWidget(self.leftskins)
        self.rightskins = QtWidgets.QPushButton(self.layoutWidget1)
        self.rightskins.setObjectName("rightskins")
        self.verticalLayout.addWidget(self.rightskins)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Магазин"))
        self.clicklb.setText(_translate("MainWindow", "Клик"))
        self.autoclickup.setText(_translate("MainWindow", "150"))
        self.energyup.setText(_translate("MainWindow", "10"))
        self.clickup.setText(_translate("MainWindow", "50"))
        self.label.setText(_translate("MainWindow", "Энергия"))
        self.autolb.setText(_translate("MainWindow", "Автоклик в секунду"))
        item = self.Leaderboard.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.Leaderboard.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.Leaderboard.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.Leaderboard.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.Leaderboard.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.Leaderboard.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.Leaderboard.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.Leaderboard.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.Leaderboard.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.Leaderboard.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.Leaderboard.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Логин"))
        item = self.Leaderboard.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Пройдено"))
        item = self.Leaderboard.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Деньги "))
        item = self.Leaderboard.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Клик"))
        item = self.Leaderboard.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Автоклик"))
        __sortingEnabled = self.Leaderboard.isSortingEnabled()
        self.Leaderboard.setSortingEnabled(False)
        self.Leaderboard.setSortingEnabled(__sortingEnabled)
        self.progressBar.setFormat(_translate("MainWindow", "%p%"))
        self.buyskin.setText(_translate("MainWindow", "Купить"))
        self.changeskin.setText(_translate("MainWindow", "Установить"))
        self.leftskins.setText(_translate("MainWindow", "<--"))
        self.rightskins.setText(_translate("MainWindow", "-->"))
