from PyQt5 import QtCore, QtGui, QtWidgets


class TutorialForm(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1383, 394)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1383, 394))
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("TOYZ")
        font.setPointSize(10)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("TOYZ")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1090, 1826))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.imgsettings = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.imgsettings.setText("")
        self.imgsettings.setPixmap(QtGui.QPixmap("images/Settings.png"))
        self.imgsettings.setObjectName("imgsettings")
        self.gridLayout.addWidget(self.imgsettings, 3, 0, 1, 1)
        self.imgshop = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.imgshop.setText("")
        self.imgshop.setPixmap(QtGui.QPixmap("images/Shop.png"))
        self.imgshop.setObjectName("imgshop")
        self.gridLayout.addWidget(self.imgshop, 4, 0, 1, 1)
        self.imgenter = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.imgenter.setText("")
        self.imgenter.setPixmap(QtGui.QPixmap("images/Enter.png"))
        self.imgenter.setObjectName("imgenter")
        self.gridLayout.addWidget(self.imgenter, 0, 0, 1, 1)
        self.imgbclicker = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.imgbclicker.setText("")
        self.imgbclicker.setPixmap(QtGui.QPixmap("images/Bclicker.png"))
        self.imgbclicker.setObjectName("imgbclicker")
        self.gridLayout.addWidget(self.imgbclicker, 2, 0, 1, 1)
        self.imgregist = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.imgregist.setText("")
        self.imgregist.setPixmap(QtGui.QPixmap("images/Register.png"))
        self.imgregist.setObjectName("imgregist")
        self.gridLayout.addWidget(self.imgregist, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Туториал"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Приветствую вас в Best Clickere\'е!</span></p><p><span style=\" font-size:11pt;\">Здесь вы сможете убить своё время и мышку.</span></p><p><span style=\" font-size:11pt;\">На старте будет видно печеньку и зону зарядки.</span></p><p><span style=\" font-size:11pt;\">Нажимая на печеньку вы получаете внутреигровую валюту.</span></p><p><span style=\" font-size:11pt;\">Следите за энергией, она может закончится и кликать вы не сможете, </span></p><p><span style=\" font-size:11pt;\">тогда вам придётся вертеть мышку в зоне поздарядки и </span></p><p><span style=\" font-size:11pt;\">вырабатывать тем самым энергию на клики.</span></p><p><span style=\" font-size:11pt;\">В магазине вы сможете потратить внутреигровую валюту и там же</span></p><p><span style=\" font-size:11pt;\">находится прогрес бар в котором показывается ваш прогресс.</span></p><p><span style=\" font-size:11pt;\">Прогресс повышается за счёт покупки скинов. Скины это </span></p><p><span style=\" font-size:11pt;\">изображения которые заменяют фото на кнопке для клика</span></p><p><span style=\" font-size:11pt;\">В настройках можно изменить уровень громкости и</span></p><p><span style=\" font-size:11pt;\">очистить/удалить аккаунт. </span></p><p><span style=\" font-size:11pt;\">На клавиши N - вкл/выкл звук и M - вкл/выкл музыку.<br/></span></p></body></html>"))
